name: dump

on:
  push:

jobs:
  dump:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Delete old file
        run: rm -f helper.php

      - name: dump
        run: php dump.php

      # - name: build doctum docs
      #   uses: sudo-bot/action-doctum@v5
      #   with:
      #     config-file: .doctum.php
      #     method: "update"

      - uses: stefanzweifel/git-auto-commit-action@v4
